# 01. Numpy - Numerical Python

In [1]:
# de facto standard
import numpy as np

### 1. ndarray (Numpy Dimensional Array)

In [2]:
a = np. array([1, 4, 5, 8], float)
print (a)

[1. 4. 5. 8.]


In [3]:
a[3], a.dtype, a.shape

(8.0, dtype('float64'), (4,))

In [ ]:
### 2. Array shape

In [5]:
# 1차원 - vector
a = np.array([1, 4, 5, 8], float)

In [9]:
# 2차원 - matrix
m = [[1,4],[5,8]]
b = np.array(m,float)
print(b)

[[1. 4.]
 [5. 8.]]


In [11]:
# 3차원 - tensor
t = [ [[1,4],[5,8]], [[11,14],[15,18]] ]
c = np.array(t,float)
c

array([[[ 1.,  4.],
        [ 5.,  8.]],

       [[11., 14.],
        [15., 18.]]])

In [12]:
a.shape, b.shape, c.shape

((4,), (2, 2), (2, 2, 2))

In [13]:
# ndim - 몇 차원인지?
a.ndim, b.ndim, c.ndim

(1, 2, 3)

In [14]:
# size - element의 개수?
a.size, b.size, c.size

(4, 4, 8)

In [15]:
# data type(dtype)
c = np.array(t,dtype=np.float32)
c

array([[[ 1.,  4.],
        [ 5.,  8.]],

       [[11., 14.],
        [15., 18.]]], dtype=float32)

- reshape: size는 동일(element의 개수는 변하지 않음)

In [17]:
c.reshape(2,4)

array([[ 1.,  4.,  5.,  8.],
       [11., 14., 15., 18.]], dtype=float32)

In [18]:
c.reshape(8,)

array([ 1.,  4.,  5.,  8., 11., 14., 15., 18.], dtype=float32)

In [19]:
# -1은 한번만 사용 가능
c.reshape(-1, 4)

array([[ 1.,  4.,  5.,  8.],
       [11., 14., 15., 18.]], dtype=float32)

In [20]:
# flatten - 1차원으로 만들어줌
c.flatten()

array([ 1.,  4.,  5.,  8., 11., 14., 15., 18.], dtype=float32)

### 3. Indexing and Slicing

In [21]:
a=np.arange(6)    #a.np.array(range(6))
a

array([0, 1, 2, 3, 4, 5])

In [22]:
a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [23]:
# 행,열 인덱싱
a[0][1]

1

In [24]:
# numpy에서의 인덱싱
a[0, 1]

1

In [26]:
# 리스트와는 달리 행,열 모두에 대해 슬라이싱 가능
a[:,:2]

array([[0],
       [3]])

In [28]:
b= np.arange(16).reshape(-1,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [33]:
# 5 6
# 9 10 출력하려면?

b[1:3,1:3]  #행은 1,2   열은 1,2

array([[ 5,  6],
       [ 9, 10]])

In [34]:
# 0 1
# 4 5
# 8 9
b[0:3,0:2]    # 행은 0,1,2  열은 0,1
b[:3, :2]     # 0은 생략 가능

array([[0, 1],
       [4, 5],
       [8, 9]])

In [35]:
# 세번째 열까지는 X, 마지막 열은 Y
X, Y = b[:, :-1], b[:, -1]
X.shape, Y.shape

((4, 3), (4,))

### 4. Creation

In [36]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [37]:
np.arange(0, 1.1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [38]:
np.arange(0, 1.1, 0.1).tolist()    #리스트로 만들기

[0.0,
 0.1,
 0.2,
 0.30000000000000004,
 0.4,
 0.5,
 0.6000000000000001,
 0.7000000000000001,
 0.8,
 0.9,
 1.0]

In [40]:
# 실수는 우리가 원하는 값을 정확하게 표현하지 못함
np.arange(0, 1.1, 0.1).tolist()[3] == 0.3

False

In [44]:
# 두 실수의 비교는 차이가 아주 작은지를 물어보는 것이 올바른 방법임
np.abs(np.arange(0, 1.1, 0.1).tolist()[3]-0.3) < 1e-8

True

In [49]:
# ones, zeros, empty
a = np.zeros((5,), dtype = np.int8)
a

array([0, 0, 0, 0, 0], dtype=int8)

In [46]:
b = np.ones((2,4), dtype = np.int8)
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int8)

In [47]:
np.empty((2,5))

array([[0.1, 0.2, 0.3, 0.4, 0.5],
       [0.6, 0.7, 0.8, 0.9, 1. ]])

In [50]:
a = np.arange(24).reshape(4,-1)
np.ones_like(a)

array([[1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1]])

In [51]:
a = np.arange(24).reshape(4,-1)
np.zeros_like(a)

array([[0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [52]:
# 단위 행렬: identity
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [53]:
# eye - 대각선이 1인 행렬
np.eye(3,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.]])

In [55]:
np.eye(N=3,M=5,k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.]])

In [56]:
np.eye(3,5,2)

array([[0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
- Random sampling

In [57]:
# 균등 분포
np.random.seed(2021)
np.random.uniform(0,1,10).reshape(2,5)

array([[0.60597828, 0.73336936, 0.13894716, 0.31267308, 0.99724328],
       [0.12816238, 0.17899311, 0.75292543, 0.66216051, 0.78431013]])

In [62]:
# 정규 분포
np.random.normal(0, 1, 10).reshape(2,5)

array([[ 1.00324527, -0.36644983,  1.12805168,  0.7925838 , -1.75084239],
       [-0.80886945, -1.41260181, -0.8030097 ,  0.79828047,  1.75599622]])

In [61]:
# 이항분포, 포아송분포(poison), t-분포(standard_t), F-분포(f)
np.random.binomial(100, 1/6., 10)

array([16, 20, 12, 21, 19, 19, 11, 17, 20, 14])

In [59]:
np.random.binomial(100, 0.5, 10)

array([42, 46, 53, 57, 48, 57, 44, 40, 57, 54])