In [16]:
import numpy as np

### 5. Operation

In [2]:
a=np.arange(1,11,dtype=np.float32)
a.sum()

55.0

In [3]:
b=np.arange(1,13).reshape(3,4)
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
# 세로 방향의 합
b.sum(axis = 0)

array([15, 18, 21, 24])

In [4]:
# 가로 방향의 합
b.sum(axis = 1)

array([10, 26, 42])

In [6]:
# 평균
b.mean(axis=0), b.mean(axis=1)

(array([5., 6., 7., 8.]), array([ 2.5,  6.5, 10.5]))

In [7]:
# 표준편차
b.std(axis=0), b.std(axis=1)

(array([3.26598632, 3.26598632, 3.26598632, 3.26598632]),
 array([1.11803399, 1.11803399, 1.11803399]))

In [10]:
# 수학 함수
X = np.arange(-1, 1.01, 0.01)
X.size

201

In [18]:
import math
Y = np.exp(X)

In [19]:
# sigmoid 함수
Y = 1./(1.+np.exp(-X))

- Concatenate

In [20]:
a = np.arange(1,5).reshape(2,2)
b = np.array([[5,6]])
np.vstack((a,b))

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
np.concatenate((a,b), axis = 0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [22]:
# 전치행렬(transpose)
b.T

array([[5],
       [6]])

In [24]:
np.concatenate((a,b.T), axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [ ]:
np.hstack((a,b.T))

### 6. Array operation

In [25]:
# element-wise operation
a + a

array([[2, 4],
       [6, 8]])

In [26]:
a - a

array([[0, 0],
       [0, 0]])

In [27]:
a * a

array([[ 1,  4],
       [ 9, 16]])

In [28]:
a / a

array([[1., 1.],
       [1., 1.]])

- dot product

In [29]:
a = np.arange(1,7).reshape(2,3)
a.dot(a.T)

array([[14, 32],
       [32, 77]])

In [30]:
np.dot(a, a.T)

array([[14, 32],
       [32, 77]])

- Broadcasting (Shape이 다른 배열간 연산 지원)

In [32]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
a + 10

array([[11, 12, 13],
       [14, 15, 16]])

In [33]:
a * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [34]:
a ** 2

array([[ 1,  4,  9],
       [16, 25, 36]], dtype=int32)

In [35]:
a + np.array([10,20,30])

array([[11, 22, 33],
       [14, 25, 36]])

In [ ]:
### 7. Comparison

In [36]:
a = np.arange(5)
np.all(a), np.any(a)

(False, True)

In [37]:
a

array([0, 1, 2, 3, 4])

In [38]:
a > 2

array([False, False, False,  True,  True])

In [39]:
a[a>2]

array([3, 4])

- logical operation

In [42]:
a = np.arange(5)
b = np.logical_and(a>0, a<3)
b

array([False,  True,  True, False, False])

In [43]:
np.logical_not(b)

array([ True, False, False,  True,  True])

In [44]:
c = np.logical_not(b)
c

array([ True, False, False,  True,  True])

In [45]:
np.logical_or(b,c)

array([ True,  True,  True,  True,  True])

In [46]:
np.logical_xor(b,c)

array([ True,  True,  True,  True,  True])

In [47]:
a = np.arange(5)
np.where(a>2)

(array([3, 4], dtype=int64),)

- NaN (Not a Number), Inf(Infinite)

In [48]:
a = np.array([1, np.NaN, np.Inf], float)
a

array([ 1., nan, inf])

In [50]:
np.isnan(a), np.isfinite(a)

(array([False,  True, False]), array([ True, False, False]))

- argmax, argmin (array내 최대값 또는 최소값의 index를 리턴)


In [53]:
a=np.arange(6)
np.argmax(a), np.argmin(a)

(5, 0)

In [54]:
b=np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
np.argmax(b, axis = 0)

In [ ]:
np.argmin(b, axis=1)