In [2]:
import numpy as np

In [ ]:
### 8. Boolean and Fancy Index

In [3]:
np.random.seed(2021)
a = np.random.uniform(1,10,4)
a

array([6.45380451, 7.60032425, 2.25052441, 3.81405775])

In [5]:
a > 3

array([ True,  True, False,  True])

In [6]:
# 값이 3을 초과하는 element만 가져옴
# Boolean indexing
a[a>3]

array([6.45380451, 7.60032425, 3.81405775])

- Fancy index

In [7]:
a=np.arange(1,5)*2
a

array([2, 4, 6, 8])

In [8]:
b=np.array([0,1,3,2,1,3])
a[b]   # b 배열의 값을 인덱스로 하여 a의 값들을 추출함

array([2, 4, 8, 6, 4, 8])

In [15]:
a=np.arange(8).reshape(2,4)
a

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [16]:
b = np.array([0,0,1,1,0])
c = np.array([0,2,3,1,2])
a[b,c]  # b를 row index, c를 column index로 변환하여 표시

array([0, 2, 7, 5, 2])