### 연습문제

### 1. 넘파이를 사용하여 다음과 같은 행렬을 만드시오.


In [ ]:
# 10 20 30 40
# 50 60 70 80

In [2]:
import numpy as np

In [5]:
print(np.array([[10,20,30,40],[50,60,70,80]], int))

[[10 20 30 40]
 [50 60 70 80]]


### 2. 다음 행렬과 같은 행렬이 있다.


In [ ]:
# m = np.array([[ 0, 1, 2, 3, 4], 
# [5, 6, 7, 8, 9], 
# [10, 11, 12, 13, 14]])

In [7]:
m = np.array([[ 0, 1, 2, 3, 4],
[5, 6, 7, 8, 9],
[10, 11, 12, 13, 14]])

In [9]:
# 1) 이 행렬에서 값 7 을 인덱싱한다.
m[1][2]

7

In [10]:
# 2) 이 행렬에서 값 14 을 인덱싱한다.
m[2][4]

14

In [12]:
# 3) 이 행렬에서 배열 [6, 7] 을 슬라이싱한다.
print(m[1, 1:3])

[6 7]


In [16]:
# 4) 이 행렬에서 배열 [7, 12] 을 슬라이싱한다.
print(m[1:3, 2])

[ 7 12]


In [19]:
# 5) 이 행렬에서 배열 [[3, 4], [8, 9]] 을 슬라이싱한다.
print(m[0:2, 3:])

[[3 4]
 [8 9]]


### 3. 2번의 행렬 m을 1차원 벡터 f 로 변환한 후 다음의 문제를 푸시오.

In [24]:
f = m.flatten()


In [33]:
# 1) 이 배열에서 3의 배수를 찾아라.
np.where(f % 3 == 0)

(array([ 0,  3,  6,  9, 12], dtype=int64),)

In [25]:
# 2) 이 배열에서 4로 나누면 1이 남는 수를 찾아라.
np.where(f % 4 == 1)

(array([ 1,  5,  9, 13], dtype=int64),)

In [30]:
# 3) 이 배열에서 3으로 나누면 나누어지고 4로 나누면 1이 남는 수를 찾아라.
np.where((f % 3 ==0) & (f % 4 == 1))

(array([9], dtype=int64),)

### 4. 값을 직접 입력하지 말고 아래 행렬을 만드시오.


In [ ]:
# 2, 1, 0, 0, 0
# 3, 2, 1, 0, 0
# 0, 3, 2, 1, 0
# 0, 0, 3, 2, 1
# 0, 0, 0, 3, 2

In [62]:
np.eye(5, 5, k=1) + np.identity(5)*2 + np.eye(5,5,k=-1)*3

array([[2., 1., 0., 0., 0.],
       [3., 2., 1., 0., 0.],
       [0., 3., 2., 1., 0.],
       [0., 0., 3., 2., 1.],
       [0., 0., 0., 3., 2.]])

### 5. 0에서 10까지 랜덤 실수값으로 이루어진 5 x 6 형태의 데이터 행렬을 만들고 이 데이터에 대해 다음과 같은 값을 구하시오.

In [5]:
np.random.seed(2021)
a = np.random.uniform(0,10,30).reshape(5,6).round(3)
a

array([[6.06 , 7.334, 1.389, 3.127, 9.972, 1.282],
       [1.79 , 7.529, 6.622, 7.843, 0.969, 0.586],
       [9.624, 6.166, 0.866, 5.613, 6.165, 9.638],
       [5.743, 3.712, 4.521, 2.019, 5.693, 1.951],
       [5.837, 4.763, 5.178, 8.231, 7.322, 0.691]])

In [7]:
# 1) 전체의 최댓값
np.max(a)


9.972

In [6]:
# 2) 각 행의 합
np.sum(a,axis=1)

array([29.164, 25.339, 38.072, 23.639, 32.022])

In [8]:
# 3) 각 행의 최댓값
np.max(a,axis=1)

array([9.972, 7.843, 9.638, 5.743, 8.231])

In [9]:
# 4) 각 열의 평균
np.mean(a, axis=0)

array([5.8108, 5.9008, 3.7152, 5.3666, 6.0242, 2.8296])

In [10]:
# 5) 각 열의 최솟값
np.min(a, axis=0)

array([1.79 , 3.712, 0.866, 2.019, 0.969, 0.586])

### 6. 다음 배열은 첫번째 행(row)에 학번, 두번째 행에 영어 성적, 세번째 행에 수학 성적을 적은 배열이다. 영어 성적을 기준으로 ( 각 열(column)을 ) 재정렬하시오.

In [12]:
c = np.array([[ 1, 2, 3, 4],
            [ 46, 99, 100, 71],   #이 행이 영어성적
            [ 81, 59, 90, 100]])

In [54]:
c[:, c[1].argsort()].T

array([[  1,  46,  81],
       [  4,  71, 100],
       [  2,  99,  59],
       [  3, 100,  90]])

In [13]:
# 선생님 풀이
# 오름차순
s = np.argsort(c[1])

array([0, 3, 1, 2], dtype=int64)

In [ ]:
# 내림차순
s[::-1]

In [ ]:
score[:,s]

In [ ]:
# 오름차순 한꺼번에 수행
score[:, np.argsort(c[1])]

In [ ]:
# 내림차순 한꺼번에 수행
score[:, np.argsort(c[1])][::-1]

### 7. 주사위를 100번 던지는 가상 실험을 파이썬으로 작성하고, 던져서 나오는 숫자의 평균을 구하시오.

In [20]:
np.random.seed(2021)
b = np.random.randint(1,7,100)
np.mean(b)

3.7

### 8. 가격이 10,000원인 주식이 있다. 이 주식의 일간 수익률(%)은 기댓값이 0%이고 표준편차가 1%인 표준 정규 분포를 따른다고 하자. 250일 동안의 주가를 무작위로 생성하시오.


In [30]:
# 새로운 리스트 만들지 않고 그냥 하기
x = 10000
num = 1
while num <= 250:
    x = x + 10000 * np.random.normal(0,1,1) * 0.01
    num += 1
    print(np.round(x),end=' ')

[9979.] [9862.] [9979.] [10012.] [9923.] [9866.] [9814.] [9768.] [9818.] [9829.] [9760.] [9766.] [9859.] [9730.] [9926.] [10097.] [10242.] [10304.] [10368.] [10376.] [10596.] [10576.] [10543.] [10441.] [10425.] [10276.] [10335.] [10312.] [10183.] [10365.] [10504.] [10546.] [10511.] [10543.] [10721.] [10652.] [10592.] [10624.] [10666.] [10674.] [10659.] [10635.] [10563.] [10550.] [10707.] [10828.] [10884.] [10875.] [10922.] [10956.] [10865.] [10848.] [10841.] [10806.] [10878.] [10905.] [10953.] [10790.] [10879.] [10827.] [10783.] [10858.] [10869.] [10827.] [10782.] [10742.] [10554.] [10350.] [10334.] [10388.] [10442.] [10387.] [10412.] [10494.] [10550.] [10649.] [10610.] [10413.] [10506.] [10412.] [10269.] [10261.] [10293.] [10172.] [10094.] [10094.] [10075.] [10163.] [10406.] [10364.] [10445.] [10292.] [10313.] [10263.] [10207.] [10327.] [10265.] [10224.] [10222.] [10315.] [10517.] [10482.] [10442.] [10375.] [10242.] [10175.] [10040.] [9904.] [9860.] [9840.] [9699.] [9775.] [9728.] [95

In [31]:
x = 10000
p = []
num = 1
while num <= 250:
    x = x + 10000 * np.random.normal(0,1,1)[0] * 0.01
    num += 1
    p.append(np.round(x))
#print(p) -- 이렇게 하면 뒤에 .0이 붙고, 행과 열 간격이 일정하지 않아 가독성 떨어짐

stock = np.array(p, int)
print(stock)
#print(stock[:10])-- 앞에 10개만 출력


[10068. 10075. 10070. 10069. 10060. 10104. 10032.  9884.  9845.  9882.
  9912. 10072. 10187. 10286. 10321. 10290. 10206. 10290. 10116. 10176.
 10141. 10018.  9871.  9977.  9884.  9809.  9805.  9980.  9986. 10083.
 10293. 10382. 10522. 10522. 10718. 10592. 10591. 10686. 10626. 10774.
 10809. 10734. 10886. 11020. 11038. 11000. 10821. 10954. 10910. 10866.
 10769. 10597. 10535. 10552. 10678. 10701. 10725. 10948. 11127. 11035.
 11074. 10931. 10842. 10810. 11062. 11016. 10982. 10972. 11030. 11114.
 11119. 11392. 11658. 11669. 11700. 11457. 11451. 11455. 11440. 11451.
 11494. 11486. 11561. 11613. 11683. 11605. 11482. 11383. 11404. 11433.
 11386. 11318. 11452. 11466. 11431. 11462. 11332. 11475. 11376. 11293.
 11377. 11397. 11174. 11147. 11320. 11157. 11284. 11261. 11367. 11425.
 11517. 11670. 11854. 11872. 11903. 11946. 12058. 12210. 12166. 12390.
 12436. 12481. 12449. 12323. 12386. 12384. 12440. 12426. 12282. 12254.
 12380. 12315. 12224. 12212. 12200. 12170. 11962. 11917. 12031. 12173.
 12189

In [24]:
np.size(stock)

250

In [104]:
np.random.normal(0,1,1)

array([1.56634309])

In [105]:
np.random.normal(0,1,1)[0]  #array 없이 숫자만 나오도록 설정

0.340841880086619